LIBMAKE+=../libraries/l3g4200d/Makefile
CPPSRC+=../libraries/l3g4200d/l3g4200d.cpp
CPPSRC+=../libraries/l3g4200d/l3g4200d_common.cpp
include ../libraries/spi/Makefile
EXTRAINCDIRS+=../libraries/l3g4200d/

../libraries/l3g4200d.cpp: extract_str.inc

