LIBMAKE+=../libraries/riegel/Makefile
SRC+=../libraries/riegel/byteordering.c
SRC+=../libraries/riegel/fat.c
SRC+=../libraries/riegel/sd_raw.c
SRC+=../libraries/riegel/partition.c
EXTRAINCDIRS+=../libraries/riegel/

CDEFS += -DRIEGEL -DLITTLE_ENDIAN=1

