LIBMAKE+=../libraries/riegel/Makefile
CSRC+=../libraries/riegel/byteordering.c
CSRC+=../libraries/riegel/fat.c
CSRC+=../libraries/riegel/sd_raw.c
CSRC+=../libraries/riegel/partition.c
EXTRAINCDIRS+=../libraries/riegel/

