#Since the whole point of this project is to test the LPC4078, set the submodel here
SUBMDL=LPC4078
OPTLEVEL = 3
PROJECT_BRIEF="Serial port test, mostly only useful for LPC4078"
HWDESCCSV=Loginator2368Hardware.csv Loginator2368Onboard.csv
#include ../libraries/LPCduino/Makefile
#include ../libraries/peripherals/Serial/Makefile
#include ../libraries/dump/Makefile
#include ../libraries/hardwareDesc/Makefile
include ../libraries/System/Makefile



