PROJECT_BRIEF="Blank sketch, suitable for copying, pasting, and modifying"
include ../libraries/Serial/Makefile
include ../libraries/float/Makefile
include ../libraries/crc/Makefile
include ../libraries/System/Makefile

