LIBMAKE+=../libraries/msc/Makefile
CPPSRC+=../libraries/msc/main_msc.cpp
CPPSRC+=../libraries/msc/msc_bot.cpp
CPPSRC+=../libraries/msc/msc_scsi.cpp
CPPSRC+=../libraries/msc/serial_fifo.cpp
CPPSRC+=../libraries/msc/usbcontrol.cpp
CPPSRC+=../libraries/msc/usbhw_lpc.cpp
CPPSRC+=../libraries/msc/usbinit.cpp
CPPSRC+=../libraries/msc/usbstdreq.cpp
include ../libraries/sdhc/Makefile
EXTRAINCDIRS+=../libraries/msc/
