LIBMAKE+=../libraries/Wire/HardTwoWire/Makefile
CPPSRC+=../libraries/Wire/HardTwoWire/HardTwoWire.cpp
include ../libraries/gpio/Makefile
include ../libraries/Wire/Makefile
EXTRAINCDIRS+=../libraries/Wire/HardTwoWire/
