LIBMAKE+=../libraries/file/FileCircular/Makefile
#CPPSRC+=../libraries/file/FileCircular/FileCircular.cpp
EXTRAINCDIRS +=../libraries/file/FileCircular/

include ../libraries/Circular/Makefile
#include the correct Makefile for the file library (Riegel or Kwan)
#before including this Makefile
#include ../libraries/file/fat/Makefile


