LIBMAKE+=../libraries/Serial/Makefile
CPPSRC+=../libraries/Serial/Serial.cpp
include ../libraries/gpio/Makefile
include ../libraries/Print/Makefile
include ../libraries/Circular/Makefile
EXTRAINCDIRS +=../libraries/Serial/

