LIBMAKE+=../libraries/FileCircular/Makefile
CPPSRC+=../libraries/FileCircular/FileCircular.cpp
EXTRAINCDIRS +=../libraries/FileCircular/

include ../libraries/Circular/Makefile
include ../libraries/fat/Makefile


