HARDWARE=LOGINATOR
ATTACH=Loginator1.1.brd Loginator1.1.sch 11Dof.brd 11Dof.sch Apid.ods
include ../libraries/LPCduino/Makefile
include ../libraries/Serial/Makefile
include ../libraries/Task/Makefile
include ../libraries/Wire/StateTwoWire/Makefile
include ../libraries/bmp180/Makefile
include ../libraries/hmc5883/Makefile
include ../libraries/adxl345/Makefile
include ../libraries/l3g4200d/Makefile
include ../libraries/gps/Makefile
include ../libraries/dump/Makefile
include ../libraries/packet/Makefile
include ../libraries/fat/Makefile
include ../libraries/FileCircular/Makefile
include ../libraries/System/Makefile


