HARDWARE=LOGINATOR
PROJECT_BRIEF="Blank sketch, suitable for copying, pasting, and modifying"
include ../libraries/LPCduino/Makefile
include ../libraries/Serial/Makefile
include ../libraries/System/Makefile


