PROJECT_BRIEF="Blank sketch, suitable for copying, pasting, and modifying"
include ../libraries/gpio/Makefile
include ../libraries/PWM/Makefile
include ../libraries/Serial/Makefile
include ../libraries/System/Makefile


