PROJECT_BRIEF="Blank sketch, suitable for copying, pasting, and modifying"
include ../libraries/LPCduino/Makefile
include ../libraries/PWM/Makefile
include ../libraries/hmc5883/Makefile
include ../libraries/Serial/Makefile
include ../libraries/sdhc/Makefile
include ../libraries/fat/Makefile
include ../libraries/Wire/StateTwoWire/Makefile
include ../libraries/System/Makefile

