LIBMAKE+=../libraries/hmc5883/Makefile
include ../libraries/packet/ccsds/Makefile
CPPSRC+=../libraries/hmc5883/hmc5883.cpp
EXTRAINCDIRS+=../libraries/hmc5883/

../libraries/hmc5883/hmc5883.cpp: extract_str.inc

