LIBMAKE+=../libraries/StateTwoWire/Makefile
CPPSRC+=../libraries/StateTwoWire/StateTwoWire.cpp
include ../libraries/gpio/Makefile
include ../libraries/Wire/Makefile
EXTRAINCDIRS+=../libraries/StateTwoWire/
