CPPSRC+=../libraries/file/fat/cluster.cpp
CPPSRC+=../libraries/file/fat/direntry.cpp
CPPSRC+=../libraries/file/fat/file.cpp
LIBMAKE+=../libraries/file/fat/Makefile
EXTRAINCDIRS+=../libraries/file/fat/

include ../libraries/file/Partition/Makefile

