LIBMAKE+=../libraries/Wire/peripherals/HardTwoWire/Makefile
CPPSRC+=../libraries/Wire/peripherals/HardTwoWire/HardTwoWire.cpp
include ../libraries/peripherals/gpio/Makefile
include ../libraries/peripherals/Wire/Makefile
EXTRAINCDIRS+=../libraries/peripherals/Wire/HardTwoWire/
