LIBMAKE+=../libraries/peripherals/Serial/Makefile
CPPSRC+=../libraries/peripherals/Serial/Serial.cpp
include ../libraries/gpio/Makefile
include ../libraries/Print/Makefile
include ../libraries/Circular/Makefile
EXTRAINCDIRS +=../libraries/peripherals/Serial/

