LIBMAKE+=../libraries/sensors/hmc5883/Makefile
include ../libraries/packet/ccsds/Makefile
#CPPSRC+=../libraries/sensors/hmc5883/hmc5883.cpp
EXTRAINCDIRS+=../libraries/sensors/hmc5883/

../libraries/sensors/hmc5883/hmc5883.h: ../libraries/sensors/hmc5883/hmc5883.cpp

../libraries/sensors/hmc5883/hmc5883.cpp: extract_str.INC

