LIBMAKE+=../libraries/sensors/ad799x/Makefile
#CPPSRC+=../libraries/sensors/ad799x/ad799x.cpp
include ../libraries/peripherals/Serial/Makefile
include ../libraries/Task/Makefile
include ../libraries/packet/Makefile
EXTRAINCDIRS+=../libraries/sensors/ad799x/


