LIBMAKE+=../libraries/sensors/bmp180/Makefile
#CPPSRC+=../libraries/sensors/bmp180/bmp180.cpp
include ../libraries/peripherals/Serial/Makefile
include ../libraries/Task/Makefile
include ../libraries/packet/Makefile
EXTRAINCDIRS+=../libraries/sensors/bmp180/


