PROJECT_BRIEF="Blank sketch, suitable for copying, pasting, and modifying"

ROPE=Validation
ROPEROOT=Validation
#ROPE=Luminary131
#ROPEROOT=MAIN

include ../libraries/agc/Makefile
include ../libraries/System/Makefile


