LIBMAKE+=../libraries/sensors/l3g4200d/Makefile
CPPSRC+=../libraries/sensors/l3g4200d/l3g4200d.cpp
CPPSRC+=../libraries/sensors/l3g4200d/l3g4200d_common.cpp
include ../libraries/peripherals/spi/Makefile
EXTRAINCDIRS+=../libraries/sensors/l3g4200d/

../libraries/sensors/l3g4200d.cpp: extract_str.INC

