MEDIA="/media/MICROSD 8GB"
#EAGLE=Rocketometer.brd Rocketometer.sch

include ../libraries/Serial/Makefile
include ../libraries/Task/Makefile
include ../libraries/bmp180/Makefile
include ../libraries/hmc5883/Makefile
include ../libraries/adxl345/Makefile
include ../libraries/l3g4200d/Makefile

include ../libraries/System/Makefile

