LIBMAKE+=../libraries/HardTwoWire/Makefile
CPPSRC+=../libraries/HardTwoWire/HardTwoWire.cpp
include ../libraries/gpio/Makefile
include ../libraries/Wire/Makefile
EXTRAINCDIRS+=../libraries/HardTwoWire/
