PROJECT_BRIEF="Blank sketch, suitable for copying, pasting, and modifying"
include ../libraries/LPCduino/Makefile
include ../libraries/peripherals/Serial/Makefile
include ../libraries/dump/Makefile
include ../libraries/System/Makefile


