MEDIA="/media/MICROSD 8GB"
#EAGLE=Loginator1.1.brd Loginator1.1.sch
include ../libraries/Serial/Makefile
include ../libraries/dump/Makefile
include ../libraries/usb/Makefile
include ../libraries/fat/Makefile

include ../libraries/System/Makefile

