MEDIA="/media/MICROSD 8GB"

include ../libraries/Serial/Makefile
include ../libraries/dump/Makefile
include ../libraries/usb/Makefile
include ../libraries/fat/Makefile

include ../libraries/System/Makefile

