CPPSRC+=../libraries/LPCduino/LPCduino.cpp
LIBMAKE+=../libraries/LPCduino/Makefile
EXTRAINCDIRS+=../libraries/LPCduino/
include ../libraries/peripherals/gpio/Makefile
include ../libraries/PWM/Makefile
