LIBMAKE+=../libraries/file/sdhc/Makefile
#CPPSRC+=../libraries/file/sdhc/sdhc.cpp
include ../libraries/peripherals/spi/Makefile
include ../libraries/dump/Makefile
include ../libraries/Circular/Makefile
include ../libraries/Time/Makefile
EXTRAINCDIRS+=../libraries/file/sdhc/

