function F = F_IMU(in1,gz)
%F_IMU
%    F = F_IMU(IN1,GZ)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    14-Apr-2011 20:56:48

fp ewh = x->data[ 0]*0.5;
fp exh = x->data[ 1]*0.5;
fp eyh = x->data[ 2]*0.5;
fp ezh = x->data[ 3]*0.5;
fp wx  = x->data[ 4];
fp wy  = x->data[ 5];
fp wz  = x->data[ 6];
fp bx  = x->data[ 7];
fp by  = x->data[ 8];
fp bz  = x->data[ 9];
fp vx  = x->data[10];
fp vy  = x->data[11];
fp vz  = x->data[12];
fp aix = x->data[13];
fp aiy = x->data[14];
fp aiz = x->data[15];
F->data[ 0] = -exh*wx-eyh*wy-ezh*wz;
F->data[ 1] =  ewh*wx+eyh*wz-ezh*wy;
F->data[ 2] =  ewh*wy-exh*wz+ezh*wx;
F->data[ 3] =  ewh*wz+exh*wy-eyh*wx;
F->data[ 4] = 0.0;
F->data[ 5] = 0.0;
F->data[ 6] = 0.0;
F->data[ 7] = vx;
F->data[ 8] = vy;
F->data[ 9] = vz;
F->data[10] = aix;
F->data[11] = aiy;
F->data[12] = aiz;
F->data[13] = 0.0;
F->data[14] = 0.0;
F->data[15] = 0.0;
