function g = g_IMU(in1,Bix,Biy,Biz,gz)
%G_IMU
%    G = G_IMU(IN1,BIX,BIY,BIZ,GZ)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    14-Apr-2011 20:56:48
c00=(ew*ew+ex*ex-ey*ey-ez*ez);c01=2*(ew*ez + ex*ey);        c02=2*(ex*ez-ew*ey);
c10=2*(ex*ey-ew*ez);          c11=(ew*ew-ex*ex+ey*ey-ez*ez);c12=2*(ew*ex+ey*ez);
c20=2*(ew*ey+ex*ez);          c21=2*(ey*ez-ew*ex);          c22=(ew*ew-ex*ex-ey*ey+ez*ez);

 
                                                                                         wx
                                                                                         wy
                                                                                         wz
        Bix*c00+Biy*c01+Biz*c02 
        Bix*c10+Biy*c11+Biz*c22 
        Bix*c20+Biy*c21+Biz*c22
        aix*c00+aiy*c10+(aiz+gz)*c20
        aix*c01+aiy*c11+(aiz+gz)*c21
        aix*c02+aiy*c12+(aiz+gz)*c22
