function H = H_IMU(in1;Bix;Biy;Biz;gz)
%H_IMU
%    H = H_IMU(IN1;BIX;BIY;BIZ;GZ)

%    This function was generated by the Symbolic Math Toolbox version 5.5.
%    14-Apr-2011 20:56:49

aix = in1(14;:);
aiy = in1(15;:);
aiz = in1(16;:);
ew = in1(1;:);
ex = in1(2;:);
ey = in1(3;:);
ez = in1(4;:);
t564 = Biy*ew*2.0;
t565 = Biz*ex*2.0;
t577 = Bix*ez*2.0;
t566 = t564+t565-t577;
t567 = Biy*ex*2.0;
t568 = Bix*ex*2.0;
t569 = Biy*ey*2.0;
t570 = Biz*ez*2.0;
t571 = t568+t569+t570;
t572 = Bix*ew*2.0;
t573 = Biy*ez*2.0;
t574 = Biz*ew*2.0;
t575 = Bix*ey*2.0;
t576 = -t567+t574+t575;
t578 = Biz*ey*2.0;
t579 = aiz+gz;
t580 = ex*t579*2.0;
t581 = aiy*ex*2.0;
t582 = ew*t579*2.0;
t583 = aix*ex*2.0;
t584 = aiy*ey*2.0;
t585 = ez*t579*2.0;
t586 = t583+t584+t585;
t587 = aix*ew*2.0;
t588 = ey*t579*2.0;
t599 = aiy*ez*2.0;
t589 = t587+t588-t599;
t590 = ex*ey*2.0;
t591 = ew*ew;
t592 = ex*ex;
t593 = ey*ey;
t594 = ez*ez;
t595 = aix*ey*2.0;
t596 = aiy*ew*2.0;
t597 = aix*ez*2.0;
t598 = -t580+t596+t597;
t600 = ew*ey*2.0;
t601 = ex*ez*2.0;
t602 = ey*ez*2.0;
H->data[0]=0.0;	H->data[1]=    0.0;	H->data[2]=    0.0;	H->data[3]=    0.0;	H->data[4]=    1.0;	H->data[5]=    0.0;    	H->data[6]=    0.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    0.0;	H->data[14]=    0.0;	H->data[15]=    0.0;
H->data[0]=    0.0;	H->data[1]=    0.0;	H->data[2]=    0.0;	H->data[3]=    0.0;	H->data[4]=    0.0;	H->data[5]=    1.0;	H->data[6]=    0.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    0.0;	H->data[14]=    0.0;	H->data[15]=    0.0;
H->data[0]=    0.0;	H->data[1]=    0.0;	H->data[2]=    0.0;	H->data[3]=    0.0;	H->data[4]=    0.0;	H->data[5]=    0.0;	H->data[6]=    1.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    0.0;	H->data[14]=    0.0;	H->data[15]=    0.0;
H->data[0]=    t572+t573-Biz*ey*2.0;	H->data[1]=    t571;	H->data[2]=    t567-Biz*ew*2.0-Bix*ey*2.0;	H->data[3]=    t566;	H->data[4]=    0.0;	H->data[5]=    0.0;	H->data[6]=    0.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    0.0;	H->data[14]=    0.0;	H->data[15]=    0.0;
H->data[0]=    t566;	H->data[1]=    t576;	H->data[2]=    t571;	H->data[3]=    -t572-t573+t578;	H->data[4]=    0.0;	H->data[5]=    0.0;	H->data[6]=    0.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    0.0;	H->data[14]=    0.0;	H->data[15]=    0.0;
H->data[0]=    t576;	H->data[1]=    -t564-t565+t577;	H->data[2]=    t572+t573-t578;	H->data[3]=    t571;	H->data[4]=    0.0;	H->data[5]=    0.0;	H->data[6]=    0.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    0.0;	H->data[14]=    0.0;	H->data[15]=    0.0;
H->data[0]=    t589;	H->data[1]=    t586;	H->data[2]=    t581+t582-aix*ey*2.0;	H->data[3]=    t580-aiy*ew*2.0-aix*ez*2.0;	H->data[4]=    0.0;	H->data[5]=    0.0;	H->data[6]=    0.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    t591+t592-t593-t594;	H->data[14]=    t590-ew*ez*2.0;	H->data[15]=    t600+t601;
H->data[0]=    t598;	H->data[1]=    -t581-t582+t595;	H->data[2]=    t586;	H->data[3]=    t589;	H->data[4]=    0.0;	H->data[5]=    0.0;	H->data[6]=    0.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    t590+ew*ez*2.0;	H->data[14]=    t591-t592+t593-t594;	H->data[15]=    t602-ew*ex*2.0;
H->data[0]=    t581+t582-t595;	H->data[1]=    t598;	H->data[2]=    -t587-t588+t599;	H->data[3]=    t586;	H->data[4]=    0.0;	H->data[5]=    0.0;	H->data[6]=    0.0;	H->data[7]=    0.0;	H->data[8]=    0.0;	H->data[9]=    0.0;	H->data[10]=    0.0;	H->data[11]=    0.0;	H->data[12]=    0.0;	H->data[13]=    -t600+t601;	H->data[14]=    t602+ew*ex*2.0;	H->data[15]=    t591-t592-t593+t594
H->data[0]=0;	H->data[1]=0;	H->data[2]=0;	H->data[3]=0;	H->data[4]=0;	H->data[5]=0;	H->data[6]=0;	H->data[7]=1;	H->data[8]=0;	H->data[9]=0;	H->data[10]=0;	H->data[11]=0;	H->data[12]=0;	H->data[13]=0;	H->data[14]=0;	H->data[15]=0;
H->data[0]=0;	H->data[1]=0;	H->data[2]=0;	H->data[3]=0;	H->data[4]=0;	H->data[5]=0;	H->data[6]=0;	H->data[7]=0;	H->data[8]=1;	H->data[9]=0;	H->data[10]=0;	H->data[11]=0;	H->data[12]=0;	H->data[13]=0;	H->data[14]=0;	H->data[15]=0;
H->data[0]=0;	H->data[1]=0;	H->data[2]=0;	H->data[3]=0;	H->data[4]=0;	H->data[5]=0;	H->data[6]=0;	H->data[7]=0;	H->data[8]=0;	H->data[9]=1;	H->data[10]=0;	H->data[11]=0;	H->data[12]=0;	H->data[13]=0;	H->data[14]=0;	H->data[15]=0;
H->data[0]=0;	H->data[1]=0;	H->data[2]=0;	H->data[3]=0;	H->data[4]=0;	H->data[5]=0;	H->data[6]=0;	H->data[7]=0;	H->data[8]=0;	H->data[9]=0;	H->data[10]=1;	H->data[11]=0;	H->data[12]=0;	H->data[13]=0;	H->data[14]=0;	H->data[15]=0;
H->data[0]=0;	H->data[1]=0;	H->data[2]=0;	H->data[3]=0;	H->data[4]=0;	H->data[5]=0;	H->data[6]=0;	H->data[7]=0;	H->data[8]=0;	H->data[9]=0;	H->data[10]=0;	H->data[11]=1;	H->data[12]=0;	H->data[13]=0;	H->data[14]=0;	H->data[15]=0;
H->data[0]=0;	H->data[1]=0;	H->data[2]=0;	H->data[3]=0;	H->data[4]=0;	H->data[5]=0;	H->data[6]=0;	H->data[7]=0;	H->data[8]=0;	H->data[9]=0;	H->data[10]=0;	H->data[11]=0;	H->data[12]=1;	H->data[13]=0;	H->data[14]=0;	H->data[15]=0;
