MEDIA="/media/MICROSD 8GB"
#EAGLE=Rocketometer.brd Rocketometer.sch

include ../libraries/Serial/Makefile
include ../libraries/Task/Makefile
include ../libraries/StateTwoWire/Makefile
include ../libraries/bmp180/Makefile
include ../libraries/hmc5883/Makefile
include ../libraries/adxl345/Makefile
include ../libraries/l3g4200d/Makefile
include ../libraries/mpu60x0/Makefile
include ../libraries/dump/Makefile
include ../libraries/packet/Makefile
include ../libraries/FileCircular/Makefile
include ../libraries/System/Makefile

