LIBMAKE+=../libraries/file/FileCircular/Makefile
CPPSRC+=../libraries/file/FileCircular/FileCircular.cpp
EXTRAINCDIRS +=../libraries/file/FileCircular/

include ../libraries/Circular/Makefile
include ../libraries/file/fat/Makefile


