LIBMAKE+=../libraries/packet/Makefile
CPPSRC+=../libraries/packet/packet.cpp
include ../libraries/Circular/Makefile
include ../libraries/float/Makefile
include ../libraries/tlmDb/Makefile
EXTRAINCDIRS +=../libraries/packet/


