LIBMAKE+=../libraries/peripherals/Wire/StateTwoWire/Makefile
#CPPSRC+=../libraries/peripherals/Wire/StateTwoWire/StateTwoWire.cpp
include ../libraries/peripherals/gpio/Makefile
include ../libraries/peripherals/Wire/Makefile
EXTRAINCDIRS+=../libraries/peripherals/Wire/StateTwoWire/
