#Functions for USB Mass Storage Device
SRC += ../libraries/usb/main_msc.c 
SRC += ../libraries/usb/msc_bot.c 
SRC += ../libraries/usb/msc_scsi.c 
SRC += ../libraries/usb/lpc2000_spi.c
SRC += ../libraries/usb/usbinit.c 
SRC += ../libraries/usb/usbhw_lpc.c 
SRC += ../libraries/usb/usbcontrol.c 
SRC += ../libraries/usb/usbstdreq.c
SRC += ../libraries/usb/sd_raw.c
SRC += ../libraries/usb/rprintf.c
EXTRAINCDIRS+=../libraries/usb
LIBMAKE+=../libraries/usb/Makefile


